frontend/urls.py
from django.urls import path
from .views import park_list, park_detail # Импортируем обе view

app_name = 'frontend'

urlpatterns = [
    # 1. URL для списка всех парков (главная страница)
    path('', park_list, name='park-list'),
    
    # 2. URL для детальной страницы ОДНОГО парка
    path('parks/<int:park_id>/', park_detail, name='park-detail'),
]

park/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ParkViewSet, EntertainmentViewSet

router = DefaultRouter()
router.register(r'parks', ParkViewSet)
router.register(r'entertainments', EntertainmentViewSet)

#юрлы
urlpatterns = [
    path('', include(router.urls))
]

vertical_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import sys
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('park.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('', include('frontend.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# для просмотра SQL-запросов при помощи django-debug-toolbar
# if settings.DEBUG and 'test' not in sys.argv:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

frontend/models.py
from django.db import models

# Create your models here.

park/models.py
from django.db import models

class Park(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название")
    city = models.CharField(max_length=100, verbose_name="Город")
    address = models.TextField(verbose_name="Адрес")
    description = models.TextField(verbose_name="Описание", null=True, blank=True)
    is_work = models.BooleanField(default=True, verbose_name="Работает")
    schedule = models.CharField(max_length=200, verbose_name="Расписание работы")
    main_photo = models.ImageField(
        verbose_name='Главное фото',
        upload_to='parks/',
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.title} ({self.city})"

class Entertainment(models.Model):
    park = models.ForeignKey(Park, on_delete=models.CASCADE, verbose_name="Парк")
    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    min_height = models.CharField(max_length= 50, verbose_name="Минимальный рост")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Цена")
    def __str__(self):
        return f"{self.title} ({self.park.title}, {self.description})"

frontend/views.py
from django.shortcuts import render
import requests

def park_list(request):
    """
    Представление для отображения списка парков.
    """
    # Делаем GET-запрос к нашему собственному API
    api_url = "http://localhost:8000/api/v1/parks/"
    try:
        response = requests.get(api_url)
        response.raise_for_status()  # Вызовет ошибку, если статус не 2xx
        parks = response.json()
    except requests.exceptions.RequestException as e:
        # Если API недоступен или вернул ошибку, показываем пустую страницу
        print(f"Could not connect to API: {e}")
        parks = []

    context = {
        'parks': parks
    }
    return render(request, 'frontend/park_list.html', context)


def park_detail(request, park_id):
    api_url_park_id = f"http://localhost:8000/api/v1/parks/{park_id}/"
    api_url_entertainments_id = f"http://localhost:8000/api/v1/entertainments/?park_id={park_id}"
    park = None
    entertainments = []
    try:
        response_park = requests.get(api_url_park_id)
        response_park.raise_for_status()
        park = response_park.json()        
    except requests.exceptions.RequestException as e:
        print(f"Couldnt get park details: {e}")

    if park:
        try:
            response_ent = requests.get(api_url_entertainments_id)
            response_ent.raise_for_status()
            entertainments = response_ent.json()
        except requests.exceptions.RequestException as e:
            print(f"Couldnt get entertainments: {e}")

    context = {
        'park': park,
        'entertainments': entertainments,
    }

    return render(request, 'frontend/park_detail.html', context)
    

park/views.py
from django.shortcuts import render
from rest_framework import viewsets, permissions
from .models import Park, Entertainment
from .serializers import ParkSerializer, EntertainmentSerializer, EntertainmentDetialSerializer
from .tasks import notify_admin_of_new_entertainment

class ParkViewSet(viewsets.ModelViewSet):
    queryset = Park.objects.all().order_by('-id')
    serializer_class = ParkSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

class EntertainmentViewSet(viewsets.ModelViewSet):
    queryset = Entertainment.objects.select_related('park').all().order_by('-id')
    serializer_class = EntertainmentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    # "влезли" в процесс создания объекта
    def perform_create(self, serializer):
        entertainment_instance = serializer.save() # сохраняет объект и возвращает нам эксемпляр
        notify_admin_of_new_entertainment.delay(entertainment_instance.id) # Мы немедленно вызываем нашу задачу, передав ей ID только что созданного развлечения

frontend/templates/frontend/base.html
<!DOCTYPE html>
<html lang="=en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Вертикаль{%endblock%}</title>
        <!-- Bootstrap CSS -->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'frontend:park-list' %}">Сеть парков "Вертикаль"</a>
            </div>

        </nav>

        <!-- Основной контент страницы -->
        <div class="container mt-4">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

frontend/templates/frontend/park_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ park.title }} - Парки</title>
    </head>
    <body>

        {% if park %}
            <h1>{{ park.title }}</h1>
            <p><strong>Город: </strong>{{park.city}}</p>
            <p><strong>Адрес: </strong>{{park.address}}</p>
            <p><strong>Расписание: </strong>{{park.schedule}}</p>
            
            <hr>
            
            <h3><strong>Описание:</strong></h3>
            <p>{{park.description}}</p>

            <h2>Развлечения в парке:</h2>
            {% if entertainments %}
                <ul>
                    {% for ent in entertainments %}
                        <li>
                            <h4> {{ent.title}} </h4>
                            <p>Цена: {{ent.price}} руб.</p>
                            <p>Минимальный рост: {{ent.min_height}}</p>
                            <p>{{ent.description}}</p>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                
                <p>К сожалению, нет информации для развлечений</p>
            {% endif %}
        {% else %}
            <!-- А вот если ПАРК НЕ НАЙДЕН, то показываем эту ошибку -->
            <h1>Парк не найден</h1>
            <p>К сожалению, мы не смогли найти информацию о парке.</p>
        {% endif %}
        <br>
            <a href="{% url 'frontend:park-list' %}">Назад к паркам</a>    
    </body>
</html>

frontend/templates/frontend/park_list.html
 <!DOCTYPE html>
   <html>
   <head>
       <title>Веревочные парки "Вертикаль"</title>
   </head>
   <body>
       <h1>Наши парки</h1>
       
       {% if parks %}
           <ul>
               {% for park in parks %}
                   <li>
                       <h2>
                            <a href="{% url 'frontend:park-detail' park.id %}">{{ park.title }}</a>
                       </h2>
                       <p><strong>Город:</strong> {{ park.city }}</p>
                       <p><strong>Адрес:</strong> {{ park.address }}</p>
                       <p><em>{{ park.description }}</em></p>
                   </li>
                   <hr>
               {% endfor %}
           </ul>
       {% else %}
           <p>К сожалению, сейчас нет информации о доступных парках.</p>
       {% endif %}

   </body>
   </html>